# Generated by Django 4.0.1 on 2022-01-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rides.user')),
                ('vehicle_type', models.CharField(max_length=10)),
                ('plate_number', models.CharField(max_length=10)),
                ('max_passenger_number', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_destination', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField()),
                ('arrival_time', models.DateTimeField(verbose_name='requested date and time')),
                ('passenger_number', models.IntegerField(default=1)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('ride_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Driver', to='rides.driver')),
                ('ride_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='rides.user')),
                ('ride_sharer1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sharer_1', to='rides.user')),
            ],
        ),
    ]
