# Generated by Django 4.0.1 on 2022-01-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_driver_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_sharable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
