# Generated by Django 4.0.1 on 2022-01-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_is_sharable_alter_ride_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_sharer2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharer_2', to='rides.user'),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_sharer3_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharer_3', to='rides.user'),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_sharer4_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharer_4', to='rides.user'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Driver', to='rides.driver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_sharer1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharer_1', to='rides.user'),
        ),
    ]
