# Generated by Django 4.0.1 on 2022-01-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_driver_special_vehicle_info_ride_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='max_passenger_number',
            field=models.IntegerField(choices=[(3, 'SEDAN 3 Passengers'), (5, 'SUV 5 Passengers')], default=5),
        ),
        migrations.AlterField(
            model_name='driver',
            name='special_vehicle_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV')], default='SUV', max_length=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_request',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV')], default='SUV', max_length=10),
        ),
    ]
