# Generated by Django 4.0.1 on 2022-01-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_alter_driver_max_passenger_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='max_passenger_number',
            field=models.IntegerField(choices=[(1, '1 Passenger'), (2, '2 Passengers'), (3, '3 Passengers'), (4, '4 Passengers'), (5, '5 Passengers')], default=5),
        ),
    ]
