# Generated by Django 4.0.1 on 2022-01-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_alter_driver_max_passenger_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
