# Generated by Django 4.0.1 on 2022-01-22 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0011_alter_driver_user_id_alter_ride_ride_driver_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='ride_owner_id',
            new_name='ride_owner',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_driver_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_sharer1_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_sharer2_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_sharer3_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_sharer4_id',
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_sharer1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sharer_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_sharer2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sharer_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_sharer3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sharer_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_sharer4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sharer_4', to=settings.AUTH_USER_MODEL),
        ),
    ]
