# Generated by Django 4.0.1 on 2022-01-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_alter_ride_ride_driver_alter_ride_ride_sharer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(help_text='Format: 2020-01-01 12:00'),
        ),
    ]
