# Generated by Django 4.0.1 on 2022-01-23 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_alter_ride_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(help_text='Format: 2022-02-14 12:00'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(check=models.Q(('arrival_time__gt', datetime.datetime(2022, 1, 23, 0, 0))), name='check_arrival_time_gt_now'),
        ),
    ]
