# Generated by Django 4.0.1 on 2022-01-26 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_remove_ride_check_arrival_time_gt_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='ride_sharer1',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_sharer2',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_sharer3',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_sharer4',
        ),
    ]
