# Generated by Django 4.0.1 on 2022-01-26 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0017_remove_ride_ride_sharer1_remove_ride_ride_sharer2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_number', models.IntegerField(default=1)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ride', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
