# Generated by Django 4.0.1 on 2022-01-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_sharerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer_number',
            field=models.IntegerField(default=0),
        ),
    ]
