# Generated by Django 4.0.1 on 2022-01-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_ride_sharer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='sharer_number',
        ),
        migrations.AddField(
            model_name='ride',
            name='total_passenger_number',
            field=models.IntegerField(default=1),
        ),
    ]
